[versions]
gradle = "8.9.3"
kotlin = "2.0.0"

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
